export const surpriseGifts = [
  {
    key: 'sugar-rush',
    number: 1,
    title: 'Sugar Rush Gate',
    gameTitle: 'Candy Crush-ish',
    gameType: 'candy',
    hint: 'Match 3+ candies in a row to score. Hit 300 points!',
    giftTitle: 'Virtual Starlight Bouquet',
    emoji: '✨',
  },
  {
    key: 'tetris-stack',
    number: 2,
    title: 'Heart Tetris',
    gameTitle: 'Tetris Block Love',
    gameType: 'tetris',
    hint: 'Rotate & stack falling blocks to clear lines! Score 100 points to win!',
    giftTitle: 'Virtual Sapphire Bouquet',
    emoji: '💎',
  },
  {
    key: 'card-castle',
    number: 3,
    title: 'Card Castle',
    gameTitle: 'Solitaire Sweetie',
    gameType: 'solitaire',
    hint: 'Move all cards to foundations. Build down alternating colors on columns!',
    giftTitle: 'Virtual Amethyst Bouquet',
    emoji: '🔮',
  },
  {
    key: 'pacman-love',
    number: 4,
    title: 'Pacman Chase',
    gameTitle: 'Grishma & Saket Love Chase',
    gameType: 'pacman',
    hint: 'Help Grishma collect all love coins & hearts while dodging playful ghosts!',
    giftTitle: 'Virtual Ruby Bouquet',
    emoji: '💖',
  },
  {
    key: 'snakey-love',
    number: 5,
    title: 'Snakey Love',
    gameTitle: 'Snake & Hearts',
    gameType: 'snake',
    hint: 'Guide the snake to eat 12 hearts. Swipe or use arrows!',
    giftTitle: 'Virtual Emerald Bouquet',
    emoji: '🍀',
  },
  {
    key: 'slide-it',
    number: 6,
    title: 'Slide It',
    gameTitle: 'The 15 Puzzle',
    gameType: 'slide',
    hint: 'Slide tiles into order: 1 through 15. Tap a tile next to the gap!',
    giftTitle: 'Virtual Moonlight Bouquet',
    emoji: '🌙',
  },
  {
    key: 'traffic-dodge',
    number: 7,
    title: 'Traffic Dodge',
    gameTitle: 'Road Runner',
    gameType: 'traffic',
    hint: 'Dodge traffic for 25 seconds! Swipe or tap arrows to switch lanes!',
    giftTitle: 'Virtual Sunrise Bouquet',
    emoji: '🌅',
  },
  {
    key: 'pipe-dream',
    number: 8,
    title: 'Pipe Dream',
    gameTitle: 'Connect The Flow',
    gameType: 'pipes',
    hint: 'Tap pipes to rotate them. Connect water from start to end!',
    giftTitle: 'Virtual Oceanic Bouquet',
    emoji: '🌊',
  },
  {
    key: 'maze-runner',
    number: 9,
    title: 'Maze Runner',
    gameTitle: 'Escape The Maze',
    gameType: 'maze',
    hint: 'Navigate the maze from start to finish. Swipe or use arrows!',
    giftTitle: 'Virtual Golden Bouquet',
    emoji: '👑',
  },
  {
    key: 'boss-level',
    number: 10,
    title: 'Boss Level',
    gameTitle: 'Final Love Quiz',
    gameType: 'quiz',
    hint: 'Answer 5 love questions about us. 3 wrong answers = start over!',
    giftTitle: 'The Ultimate Virtual Masterpiece',
    emoji: '🏆',
  },
];

export const surpriseGiftMap = new Map(surpriseGifts.map((gift) => [gift.key, gift]));
